### ISSUE TITLE
Famous Person Warning System

### ISSUE THREAD

**Issue by Wild1145** [Superior-Development/IcarusMod#10]
When a famous player (as defined by the TFM main config) joins the game, a warning should be displayed to all online players to notify them that this is a fake player joining.

**Comment by Hockeyfan360** [comment]
Again, don't assign me, but we could do something like this:

Plugin tfm = Bukkit.getServer().getPlugin("TotalFreedomMod");

EventHandler
public void famousPlayerJoin(PlayerJoinEvent event)
{
if (tfm.getConfig().getStringList("famousplayerlist).contains(event.getPlayer().getName())
{
//Warn people here.
}
}
