### ISSUE TITLE
Add CommandSpy

### ISSUE THREAD

**Issue by zD12** [Superior-Development/IcarusMod#112]
Hi there,
You should add '/cmdspy', shows all commands- excluding commands that are used for private messaging, such as, '/tell', '/msg', '/r', '/mail', and so forth.

**Comment by Wild1145** [comment]
Command spy is automatically enabled for all online admins and should not be able to be disabled to my knowledge to give admins full overview of the server.

**Comment by zD12** [comment]
Oh, on that note.  There isn't any need for the issue.
