### ISSUE TITLE
Serious issues with the weather addition

### ISSUE THREAD

**Issue by Wild1145** [Superior-Development/IcarusMod#114]
Some how this live version ended up on the beta testing server, but its causing problems.

Error log at http://pastebin.com/RaKnTbXB

**Comment by Hockeyfan360** [comment]
I swear to god, this did not happen on my private test server.

**Comment by Hockeyfan360** [comment]
@Wild1145 When did this trigger? Was it on plugin start, was it when the weather changed?

**Comment by CameronRedmore** [comment]
Dang that's an ugly error log, I'll put it in a pastebin so that it doesn't take up 95% of this page.

**Comment by CameronRedmore** [comment]
I always click the close button -_-

**Comment by Wild1145** [comment]
This appears to happen on reload, and is really causing problems now, because its just crashed the dev server...

**Comment by Wild1145** [comment]
Due to the crashing the commit has been reverted. This issue has been closed and the initial issue will be re-raised.
