### ISSUE TITLE
Nickname command

### ISSUE THREAD

**Issue by Wild1145** [Superior-Development/IcarusMod#116]
Currently the only way to edit nicknames is directly through the database. We need a command to handle this.

**Comment by mgejay** [comment]
Try using @ImALuckyGuy's

**Comment by 67** [comment]
He doesn't run Essentials or TFM so my nicking command wouldn't work properly here.

**Comment by mgejay** [comment]
@ImALuckyGuy He will be running essentials soon.

**Comment by Wild1145** [comment]
While we will be running Essentials, Nicknames and Tags are handled through the central database, meaning the chances are that other systems wont work well if at all with our setup.

**Comment by CameronRedmore** [comment]
I've already got this planned and I'll be adding nick and tag changing in game as soon as I've finished all of my GCSEs, they're taking up all of my time at the minute so after the 8th of June, I'll be free and I'll start working on this again.

**Comment by Hockeyfan360** [comment]
@CameronRedmore When you begin on this, make sure that you block the nick-name CONSOLE, it will give the nick-named player senior admin.
