### ISSUE TITLE
No Adminworld

### ISSUE THREAD

**Issue by Hockeyfan360** [Superior-Development/IcarusMod#130]
Currently, we have an admin-world toggle system done, but we have no admin-world/admin-world command set up.

**Comment by CameronRedmore** [comment]
I'll handle this, I've got code ready to use, with guest system and everything :D

**Comment by Wild1145** [comment]
I am kinda thinking we just have a separate server for admins to use within the bungee network. That way they have more freedom and are completely isolated? Opinions @Superior-Development/superior-freedom-network-pull-push

**Comment by Hockeyfan360** [comment]
I do like that idea. It would provoke some immaturity, so we may need to create a few guidelines to go along with it.

**Comment by Wild1145** [comment]
I have had a think about it and actually running an admin only server to serve as "adminworld" I think would be the best way forward. Lets give the admins a proper place to hang out.
