### ISSUE TITLE
Multiple IP Handling

### ISSUE THREAD

**Issue by Wild1145** [Superior-Development/IcarusMod#131]
Not sure if we currently support multiple IP's for admins, by the looks of the MySQL Table set-out the answer is no, if that is the case it may be worth supporting more than one somehow...

**Comment by Hockeyfan360** [comment]
I really don't know how we could do this. I dont know if String[] instead of String would work.

**Comment by Hockeyfan360** [comment]
The only solution I would have would be creating a table for ips, and we can say banned:true, but it wouldn't be a goos idea to associate them with admins.

**Comment by Wild1145** [comment]
@Superior-Development/superior-freedom-network-pull-push We still have not figured out the final implmentation of this, any suggestions anyone?

**Comment by Paul19988** [comment]
Use an Array in the MySQL table

**Comment by Wild1145** [comment]
Upon discussion with both TheCJGCJG and Varuct, we have decided not to worry about this, and let the panel handle it.
