### ISSUE TITLE
New "API"

### ISSUE THREAD

**Issue by Hockeyfan360** [Superior-Development/IcarusMod#145]
I really, really dislike the idea of adding a whole seperate package dedicated to paul, implementing things we have already done. One example are the titles. In the void methods, it asks for the title type. Useless, since it clearly states sendTitle or subtitle. I found that after looking over it for a few seconds. Regardless, I think the package should either be renamed to a sub package of the others, just named utils, or completely removed. This just makes things more complicate.

**Comment by Hockeyfan360** [comment]
Preferably, rename it to com.superior-networks.icarusmod.utils, and name classes Title, SQL, etc.

**Comment by Hockeyfan360** [comment]
@Superior-Development/superior-freedom-network-pull-push

**Comment by Paul19988** [comment]
The idea of the API is so people can easily find things that they need and those API classes will slowly grow bigger and bigger as they have multiple purposes

**Comment by Wild1145** [comment]
Depending on exactly how big it gets, one of two things will happen longer term:

1) It remains in IcarusMod and when the API is complete we refractor it to be within the com.superior-networks.icarusmod.whatever package. 

2) If it gets bigger we move it out to a separate java project that is built into Icarus as a library on compile of the plugin. 

As I say, it would have to depend on exactly how big it ends up, but I fully understand where you are coming from @Hockeyfan360, having multiple different package names is not the ideal, and is something I plan to fix with the husky thing longer term.
