### ISSUE TITLE
Un-necessary Param

### ISSUE THREAD

**Issue by Hockeyfan360** [Superior-Development/IcarusMod#146]
In the tabapi, the prefix param is un-necessary. We also don't want [Manager] Wild... In tab, it gets cut off. It would be better to just color their name with the one param. As well as that, the chatcolor param in the titleapi isn't needed. @Paul19988 Take a look at how titles were handled not too long ago.

**Comment by Paul19988** [comment]
It doesn't get cut off in 1.8 as they fixed that issue, and in my most recent patch which wasn't pushed yet changed prefix to ChatColor.
