### ISSUE TITLE
Say/smite cmd

### ISSUE THREAD

**Issue by Hockeyfan360** [Superior-Development/IcarusMod#148]

**Comment by Hockeyfan360** [comment]
The say command is actually the smite, you can copy code from a previous commit of mine to create the actual say cmd.

**Comment by Wild1145** [comment]
Oh yeah... Not quite sure how that happened...

**Comment by Wild1145** [comment]
Found it, you managed to do that in your second commit to the file here: https://github.com/Superior-Development/IcarusMod/commit/32c781ff63c0dfc7772b5eccc55b5c90b21a4527

**Comment by Hockeyfan360** [comment]
@Wild1145 I copied the class so I didn't have to do anything but change the annotation (I believe it's called, I just got back from vacation, so my brain is a bit stuffy)

**Comment by Hockeyfan360** [comment]
Pushing momentarily...

**Comment by Wild1145** [comment]
@Hockeyfan360 Would you mind taking care of this? I have quite a lot I have to do in other issues now.
