### ISSUE TITLE
Auto Settings Update

### ISSUE THREAD

**Issue by Hockeyfan360** [Superior-Development/IcarusMod#153]
Quite a few questions for @Wild1145 .

We can do this a few ways. We can store values in server memory and update those values every so often. Or, we can pull directly from the database when we need them. 

Which would you like me to implement? If the first, how often to update them?

**Comment by Wild1145** [comment]
Pull from the dB when it's needed will be better.

**Comment by Wild1145** [comment]
@Hockeyfan360
