### ISSUE TITLE
Logging of Commands, Chat and Server Messages

### ISSUE THREAD

**Issue by TheCJGCJG** [Superior-Development/IcarusMod#167]
Commands and chat as well as server messages should be logged so that web panels (or anything else for that matter) can assemble it's own log file, this will make data much easier to process and analyse after, and will also allow querying of data to allow for the logs to be easily looked over in the future.

It should store;
- Chat Messages
- Player Commands
- Server Messages
- Anything else
- Anything that would normally be saved to the latest.log file should also be saved into the database.

The server row can be used to support a multiple server setup (as IcarusFreedom required) - this will allow queries to be used to filter out the data relevant to each server (It should be noted that the database is not intended to be read using a MySQL client)

The database should use a format similar to this
<img width="758" alt="screen shot 2016-04-06 at 23 26 14" src="https://cloud.githubusercontent.com/assets/1349339/14334908/59d0aa70-fc4f-11e5-8438-7ec4c2217c78.png">

**Comment by mgejay** [comment]
Yes!!

**Comment by TheCJGCJG** [comment]
Told to re-open this by @Wild1145 

I would also like to request periodic (Maybe 15 secondly? Preferably quite frequent) logging of the following information in various tables
- Server ID (E.G. MainServer_1)
- Server RAM usage
- Server TPS (Ticks per second, or whatever that is)
- Online players (And their ranks + server they are online on)

And any other miscellaneous piece of information that could be useful in the web panel, if it looks like it could even be remotely useful, could it please be in the database.

Thanks :)

**Comment by CameronRedmore** [comment]
I'll get this done for you :)

**Comment by CameronRedmore** [comment]
Done in the latest commit, that message was all kinds of screwy...
