### ISSUE TITLE
Supporting the new "Alert" when players login

### ISSUE THREAD

**Issue by Wild1145** [Superior-Development/IcarusMod#17]
The full screen alert setup that we use on DarthCraft to welcome players back. This will probably end up having to be done by a separate plugin due to the lack of an API so far, however there may be some way through an API to do it in the future either through TFM or BukkitLib.

**Comment by Hockeyfan360** [comment]
Is this server going to be 1.8 only? If so, I could do this.

**Comment by Hockeyfan360** [comment]
@Wild1145 I can do this. Please call me via skype when you have the chance. I need to discuss something with you before I can start.

**Comment by Hockeyfan360** [comment]
This will need to be on hold until I can get my hands on an updated version of spigot.
