### ISSUE TITLE
Re-Strucure Ranks

### ISSUE THREAD

**Issue by Wild1145** [Superior-Development/IcarusMod#178]
I need to re-structure how some of the ranks work due to changes that we have decided to implement from a server perspective. I should get these done inside 24 hours.

**Comment by mainey** [comment]
So you mean, changing the admin level system works?

**Comment by mainey** [comment]
or just do a minor code cleanup ?

**Comment by Wild1145** [comment]
Changing how the admin level system actually works.

**Comment by mainey** [comment]
Shall we change it back to like this?

prettt much the same as the old one

for ex:

public static final List<String> (Ranks in here) = Arrays.asList("_MichBent");

or?

**Comment by mgejay** [comment]
@MichBent This isn't TFM. We dont and didn't use arraylists to assign ranks.

**Comment by mainey** [comment]
Eh nvm, it will conflict with the mysql database .. nvm with that. Sry
