### ISSUE TITLE
Developers Dev Mode Issue

### ISSUE THREAD

**Issue by Wild1145** [Superior-Development/IcarusMod#183]
For some reason as a Manager I cannot use /devmode developers

https://pravi.us/JEI

**Comment by mgejay** [comment]
@Wild1145 In the ICM_Rank, check if the arraylist contains the player.getName(), and if it does, return their rank as MANAGER.

**Comment by Wild1145** [comment]
I return as a manager and developer.

**Comment by Hockeyfan360** [comment]
@Wild1145 I've been kind of slow with all of the issues lately, but I've got a new adminmode/devmode system that I'll be pushing out soon. It works very differently, and it is more compact.

**Comment by Wild1145** [comment]
@Hockeyfan360 Sounds good. Lets focus that around the 1.2 release for now, I want to make sure 1.1 has no bugs, release it and then we can aim towards 1.2 ;)
