### ISSUE TITLE
Convert Devmode to MySQL

### ISSUE THREAD

**Issue by CameronRedmore** [Superior-Development/IcarusMod#185]
> There's a couple of pointless lists in ICM_Utils:
> `public static final List<String> MANAGERS = Arrays.asList("Wild1145", "Varuct", "thecjgcjg");`
> `public static final List<String> DEVELOPERS = Arrays.asList("Wild1145", "Camzie99", "Hockeyfan360");`
> These are never used since ranks are entirely done through the MySQL database. This is a ridiculously quick fix, literally just removing these two lines.

Edit: Turns out these are used in devmode. The devmode system should instead be converted to use the MySQL database rather than these static lists.

**Comment by Wild1145** [comment]
Its used as part of the devmode system... I was thinking the same myself.
