### ISSUE TITLE
Promotion Stuff not working too well

### ISSUE THREAD

**Issue by Wild1145** [Superior-Development/IcarusMod#189]
Even when it errors it says its successful... https://pravi.us/g1L

**Comment by CameronRedmore** [comment]
This was fixed a few commits back, I didn't close it in the commit message however.

**Comment by Wild1145** [comment]
This was happening on the latest stable build when trying to add someone to a lower rank like I did earlier.

**Comment by CameronRedmore** [comment]
Oh really? Well, I'll fix that now then. This is another thing that I definitely fixed. Maybe I'm calling the wrong method again :/
