### ISSUE TITLE
Random Chat Colours

### ISSUE THREAD

**Issue by Wild1145** [Superior-Development/IcarusMod#23]
Like in Camzies new madness plugin, the &- creates a random chat color. I love it and want it supported here! Maybe just in nicks to start with though if possible ;)

**Comment by CameronRedmore** [comment]
Easy as pie, well, it would be if we were using CamUtils, because that's what my LCLM uses, but I could copy over the methods, it wouldn't take too long.

**Comment by Wild1145** [comment]
@CameronRedmore I am more keen on writing as much of the code from scratch where possible, just so that everything has been designed for the plugin in mind, and it just keeps everything properly clean :)

**Comment by Hockeyfan360** [comment]
If I find time today, I will do it. Would you like this to work in commands, or just chat, or both?

**Comment by Wild1145** [comment]
Ideally both, but chat more than anything
