### ISSUE TITLE
Friend / Buddy System

### ISSUE THREAD

**Issue by Wild1145** [Superior-Development/IcarusMod#25]
More of a discussion one here, but perhaps find a way to have some sort of friend / buddy system. This way you can add a players name and IP to your "Friends" list, and when they login you are notified that they have logged in and are on the same IP as when you friended them.

**Comment by Wild1145** [comment]
@Superior-Development/java-pull-push-team @Superior-Development/java-pull-team Comments Please People.

**Comment by Hockeyfan360** [comment]
We could put a string list in the config, and create a new string list for every player that joins.

(Then, players use a command to add someone's name to the list)

**Comment by Wild1145** [comment]
@Hockeyfan360 I was leaning more towards MySQL so that it was cross server with as much as possible... That would work more if this was just for one server, but I am looking more towards scalability with this one.

**Comment by Hockeyfan360** [comment]
I completely forgot this was going to be a bungee server. I do not have a ton of experience with MySQL, I have a basic idea of what it is.

**Comment by Wild1145** [comment]
I dont have the most experience, from what I saw yesterday @CameronRedmore seems to have a good understanding of how it all works as he used it on his own plugin that uses a lot of SQL.

**Comment by Fyrsta** [comment]
I'll be happy to verify anything that you've done MySQL related in terms of efficency and security.

**Comment by Wild1145** [comment]
Bumped to the 1.0 Release.

**Comment by Fyrsta** [comment]
I don't see that this needs to be further discussed.

**Comment by Wild1145** [comment]
Valid Point. Label Removed.

**Comment by Wild1145** [comment]
Re-adding the further discussion.

I think we may well want to run this as a Bungee plugin instead of part of Icarus its self.

**Comment by CameronRedmore** [comment]
Running this as a bungee plugin would probably be massively easier than trying to make some sort of cross server shenanigans with MySQL and checking for logins on other servers and lord I don't even want to think about trying that...

**Comment by Wild1145** [comment]
Please See https://github.com/Superior-Development/PegasusMod/issues/2
