### ISSUE TITLE
Migrate Command Spy & Enhance

### ISSUE THREAD

**Issue by Wild1145** [Superior-Development/IcarusMod#26]
One of the big things that I feel command spy could use is command "highlighting" where certain key words on command spy are bold / another colour so that admins can easily see who is potentially using harmful commands. 

This will require migrating the command spy system in from TFM and being handled within this plugin. Any feedback would be appreciated.

**Comment by Wild1145** [comment]
@Superior-Development/java-pull-push-team @Superior-Development/java-pull-team Comments Please People.

**Comment by Hockeyfan360** [comment]
(I am not looking at the actual source), but before messaging to a player, we can check the commandspy string like this:

if (commandspy.contains("/commandtobehighlighted")
{
//Code here
}

Please don't assign me, I am still focusing on getting the main class to work.

**Comment by Wild1145** [comment]
@Hockeyfan360 Thats the sort of thing I am thinking, then just have a database with the keywords in so that everything is global where possible. The next thing to decide is what words we highlight.

**Comment by Hockeyfan360** [comment]
Maybe;
/smite
/pardon
/nuke
/tnt
/ci

Just a list for starters. We could make it (for some commands) so that if there are so many args (e.g. /ci <player>), it would highlight.

**Comment by Fyrsta** [comment]
Sounds like a good idea and you've come up with the best solution for it already.

**Comment by JeromSar** [comment]
Why not implement this in TFM?

**Comment by Wild1145** [comment]
@JeromSar Because long term I have no intention to stick with TFM. The long term goal is to migrate the functionality to this plugin where we can make it work better for a bungee setup, where TFM only really works for one server.
