### ISSUE TITLE
Ability To Disable AdminWorld Access

### ISSUE THREAD

**Issue by Wild1145** [Superior-Development/IcarusMod#28]
Something we had in CJFreedomMod was the ability for senior staff to enable and disable access to the admin world. Having this implemented here for developers, managers and the other higher custom ranks would be quite useful I think.

**Comment by Wild1145** [comment]
This _might_ require actually migrating admin world handling through to Icarus, while its kinda good, its also a kinda pain in the backside. I may be able to think up a easier way to do it, but otherwise thats what will have to be done. Any suggestions @Superior-Development/java-pull-push-team

**Comment by CameronRedmore** [comment]
Shove a teleport listener in there and listen for when someone teleports into the world names 'adminworld', if the adminworld is disabled, cancel the event.

**Comment by Wild1145** [comment]
@CameronRedmore Thinking about it, that would probably make more sense...

**Comment by Fyrsta** [comment]
@Wild1145 @CameronRedmore Depending on how adminworld works, a check in the command would be better.

**Comment by Wild1145** [comment]
@WickedGamingUK True, however the problem you have then is that its another modification to TFM. Thats something we are trying to keep to an absolute minimum.

**Comment by Hockeyfan360** [comment]
It could quite honestly be easier to create a boolean. Then, we create a command preprocess event. We check to see if the command starts with "admin-world." Then, we check to see if the boolean is true or false. If true, they can access the admin-world, if false, they cannot.
