### ISSUE TITLE
Move from bukkitlib for command-handling.

### ISSUE THREAD

**Issue by Hockeyfan360** [Superior-Development/IcarusMod#30]
This may sound like a bad idea, but we have been having issues preventing us from moving forward. It would not be hard to make a isManager boolean in the TFM. That way, we can do permissions. Then, it we only use BukkitLib for it's Utils, not the commands.

**Comment by Wild1145** [comment]
I am not too sure what is wrong with the existing setup to be fair. With regards to permissions you should be able to do everything you would need to do. For now it will be best to keep it simple and functional, that way we dont have to spend hours trying to figure out what we broke in custom command handling. 

Its something that I would be happy to do in the longer term, but definitely not before the 1.0 release as I just need everything to work as it should.

**Comment by Hockeyfan360** [comment]
Then what is wrong with the current setup? The commands will not load, even though we are using all of the things suggested by the BukkitLib wiki.

**Comment by Wild1145** [comment]
I tested the /icarusmod command and it works perfectly fine. The problem was on my side due to the fact that BukkitLib requires (As TFM does) for the actual command name to be lower case. We had Command_Icarus when it should have been Command_icarus  It was my mistake, and after realizing and testing, it all functions perfectly fine. You just have to remember to add it to the plugin.yml

**Comment by Hockeyfan360** [comment]
It wasn't working not too long ago. Issue closed.

**Comment by Wild1145** [comment]
This is something that I will look in to doing in the longer term, but for now it does work easier to keep where we are. I will re-open it as a issue to come back to when we are ready to make it quicker to add new commands.

**Comment by CameronRedmore** [comment]
I still think we should move to my command handling system :)

**Comment by Wild1145** [comment]
@CameronRedmore I dont mind moving over, but I really want to get the core setup done first, then when we have that setup, we can tweak with the finer workings of the plugin like command handling. I also would like to actually take a proper look at your command handling setup, as I dont believe I have any sort of source code access to the plugin. 

I am not ruling it out, but as the issue says, putting it on hold. Once we are all setup with the basics, then we will be looking to port in TFM features, and then we will review the command handling change over.

**Comment by Hockeyfan360** [comment]
We could make a class that we use to register the commands. For example, we make all command booleans static. Then, we make a command handler class, with all of the booleans inside. Then, in the main class, we put the command handler boolean in. If you need clarification, contact.

**Comment by Wild1145** [comment]
The new objective will be to migrate onto @CameronRedmore's custom command handling system for the 1.1 release.

**Comment by Wild1145** [comment]
I am currently migrating all commands onto the new system.
