### ISSUE TITLE
Switching to TFM Command Handling

### ISSUE THREAD

**Issue by Wild1145** [Superior-Development/IcarusMod#32]
As of https://github.com/Superior-Development/IcarusMod/commit/de8e0ba860c1117873530caa50a40f83565b36e7 I have been playing with the idea of using TFM command handling to manage the permissions side of our command setup. This could link in with #30 dependent on how we decide to take it forward, however utilizing TFM's command setup may prove handy in the future.

This has not been tested, it may not actually work, but either way the idea is there to help deal with some of the current limitations that we have within the plugin setup.

**Comment by Wild1145** [comment]
@Superior-Development/java-pull-push-team Opinions please everyone.

**Comment by CameronRedmore** [comment]
I believe a linkage into the TFM's command system would be a very beneficial experience however permissions could be a slight pain, we'd likely have to make individual boolean checks at the top of each command class for any custom ranks.

**Comment by Wild1145** [comment]
@CameronRedmore To be honest, I dont really imagine having a lot if any commands that will be for custom ranks, as most "Manager" commands will be just like the current seniors can do...

**Comment by Fyrsta** [comment]
This would simplify command permission checking, but you'd be more restricted.

**Comment by Wild1145** [comment]
I did have a slightly different idea, though I'm not sure if I like it. Its based off of the Minebattle way of it. When you join the server, if you run /reqsa it will check the database, and if your credentials match, if will authorise you admin. Its how MB grant OP access for administrators, but Im in two minds as to how well (if at all) we could use it here.

**Comment by Wild1145** [comment]
@CameronRedmore has created his own command processing system we will be using.
