### ISSUE TITLE
Did you test the listeners?

### ISSUE THREAD

**Issue by Hockeyfan360** [Superior-Development/IcarusMod#35]
Did you test to make sure that the listeners register? @Wild1145 

(I am asking because they did not work when I tried to implement the devmode. Other things were not registering either, and so that is why I posted)

**Comment by Wild1145** [comment]
I didnt have a chance to test them, all I did was revert to the way it used to operate. The listeners should be working just fine though.

**Comment by Hockeyfan360** [comment]
They do not work. I compiled it, and did not edit anything. I suggest we go back to manually registering them, until we can find a solution.

**Comment by Wild1145** [comment]
We are manually registering the listeners. I will check in to why it is not working shortly to find out what is going on.

**Comment by Hockeyfan360** [comment]
@Wild1145 I mean like this in the onEnable()

pm.registerEvents(new Class(), this);

**Comment by Wild1145** [comment]
@Hockeyfan360 That _should_ be happening. As I said, I will double check shortly because I thought I reverted from Reflections.
