### ISSUE TITLE
Custom Ping Message

### ISSUE THREAD

**Issue by Wild1145** [Superior-Development/IcarusMod#36]
Just like we have a custom MOTD, it would be great to make something cool happen when you hover over the ping, Spigot already shows players, and vanilla shows the ping time, but this would be quite cool and useful!

**Comment by Fyrsta** [comment]
This would be more annoying than useful. Having it show online players is really useful. Anything else would be annoying. Perhaps link it in to #25.

**Comment by Wild1145** [comment]
After trying it on DC, we found that as well. We will probably stick to just the actual MOTD part being customized and auto updating, rather than the ping message. This will also need to go into a separate bungee based plugin due to the way that bungee and bukkit handle plugins differently.
