### ISSUE TITLE
Switch to JDB Lib

### ISSUE THREAD

**Issue by Wild1145** [Superior-Development/IcarusMod#37]
As requested, we shall switch to JDBLib at some point.

**Comment by Fyrsta** [comment]
Yes, JDBLib is a good idea. The use of prepared statements will improve the security of the server.

**Comment by Fyrsta** [comment]
I don't think anything else needs to be discussed here.

**Comment by Wild1145** [comment]
@WickedGamingUK I'd like to get input from @CameronRedmore and @Hockeyfan360 as they would be the main ones to be using JDBLib over the current Husky system.

**Comment by Wild1145** [comment]
Bumped to the 1.0 Release

**Comment by Fyrsta** [comment]
Good, this will greatly improve the plugin and it will speed up future development.

**Comment by Wild1145** [comment]
@WickedGamingUK Could you explain what sort of advantage running JDBLib over Husky will actually have? Like is there any sort of advantage to doing this or what?

**Comment by Fyrsta** [comment]
@Wild1145 At the moment, it makes using Prepared Statements a lot easier and nicer, something that's good for security. Over time new things will be added to further better it. 

Also, not that it matters for this project, it doesn't need a Minecraft plugin in order to work.

**Comment by Wild1145** [comment]
@WickedGamingUK As it stands prepared statements are being used within Husky (Or so @CameronRedmore is telling me) so I cant see a major advantage to re-doing all the SQL... Not sure if thats me missing something or not though?

**Comment by Fyrsta** [comment]
@Wild1145 So apparently it is. I guess it was changed from the less secure escaping method.

Anyway, this is a far nicer way of using prepared statements, and future additions could become useful.

**Comment by Wild1145** [comment]
@WickedGamingUK I just cant see any advantage to doing a re-write of all the SQL at the current time. If the features added at a later date appear to be worthwhile for us to switch to, I think it will be considered then, however until such a time I am closing this issue.
