### ISSUE TITLE
Migrate Admin Managment

### ISSUE THREAD

**Issue by Wild1145** [Superior-Development/IcarusMod#41]
To avoid using TFM where possible, Im thinking we migrate the TFM admin setup directly to here, and just modify TFM to use this plugins system, that way we can use MySQL and do this properly.

**Comment by Fyrsta** [comment]
Good idea.

**Comment by Wild1145** [comment]
Bumped up to the 1.0 Release.

**Comment by CameronRedmore** [comment]
Half done already, just need some way to add people to admin (I'll get on that tomorrow)

**Comment by Wild1145** [comment]
Im thinking stick with /saconfig as a command name, because everyone knows it...
