### ISSUE TITLE
Migrate Banning Systems

### ISSUE THREAD

**Issue by Wild1145** [Superior-Development/IcarusMod#44]
I would like to handle the global banning of players, potentially through Icarus, but possibly through a separate bungee plugin, im not too sure yet.

**Comment by Hockeyfan360** [comment]
How would we run code on all of the servers? (Unless you were planning to add them to a config)

**Comment by Wild1145** [comment]
MySQL, so when your banned it saves to MySQL, when un-banned removed from MySQL. On player login it checkes the DB. Im thinking Bungee plugin anyway and banning from the bungee its self...
