### ISSUE TITLE
Evil cage command

### ISSUE THREAD

**Issue by Wild1145** [Superior-Development/IcarusMod#55]
We need an evil cage command to have fun with players

**Comment by Hockeyfan360** [comment]
Freeze them, play spooky noises, and have them die at random intervals?

And for the cage, maybe obsidian with slots so that people can get to him to pvp.

**Comment by Wild1145** [comment]
@Hockeyfan360 Liking the sound of that.

**Comment by Wild1145** [comment]
Superseded by #194
