### ISSUE TITLE
Move the admin world toggle out of the config

### ISSUE THREAD

**Issue by Wild1145** [Superior-Development/IcarusMod#63]
The only thing that I would like to be in the config really is the MySQL Details. Everything else really should be in MySQL.

**Comment by Hockeyfan360** [comment]
I am going to take over this issue, as I can effectively implement the auto update/settings pull.
@Wild1145 How often should settings update? every 30 seconds? Every minute? Every 10 seconds? For the best experience, I personally recommend 30 seconds, but it is completely up to you.
