### ISSUE TITLE
Errors and Question #2

### ISSUE THREAD

**Issue by mgejay** [Superior-Development/IcarusMod#69]
You have two errors in your mod so far, and it has to do with isSuperAdmin actually not existing in the AdminList file within TFM, I'm not sure if that's because of me possible having an outdated tfm.

http://gyazo.com/5c92a61b93629df4e44a5c092e99900a
http://gyazo.com/340b2787f06e00461886b2fdd6ef7620

And where is the download for reflections located?

@Wild1145

**Comment by Wild1145** [comment]
There are no errors on my end, and we are running one of the latest TFM builds. Are you sure you have imported it correctly?

**Comment by CameronRedmore** [comment]
Fixed in the latest push.
