### ISSUE TITLE
Busy System

### ISSUE THREAD

**Issue by Wild1145** [Superior-Development/IcarusMod#7]
Just like the system that DarthCraftMod supports, a busy system that will stop you being disturbed when trying to work would be handy.

**Comment by Hockeyfan360** [comment]
This should not be hard. I am not at my desktop currently, but I will get to work on this soon.

**Comment by Hockeyfan360** [comment]
@Wild1145 So do you just want it to say something in chat, or do you want it to prevent other things?

**Comment by Wild1145** [comment]
@Hockeyfan360 Take a look at the way DarthCraft does its busy system, thats the sort of thing I am looking for here.
