### ISSUE TITLE
Nothing works

### ISSUE THREAD

**Issue by mgejay** [Superior-Development/IcarusMod#70]
Nothing :D

**Comment by Wild1145** [comment]
If you're going to be helpful, you need to be more specific than that...

**Comment by mgejay** [comment]
I downloaded the release and compiled the mod, both jars commands did not work, nothing works in this plugin, review your problems.

**Comment by CameronRedmore** [comment]
Well that's funny considering everything works on mine and I believe wild's end, you do realise you need to set up a MySQL server for the plugin to work right?

**Comment by mgejay** [comment]
@CameronRedmore Yes, I have an SQL database setup and I'm saying When I put all the required jars into the plugin folder with icarus, nothing works.

**Comment by Wild1145** [comment]
Then show us some errors please.
