### ISSUE TITLE
Login Issue

### ISSUE THREAD

**Issue by Wild1145** [Superior-Development/IcarusMod#75]
> [23:26:11 INFO]: UUID of player Wild1145 is 604cbb51-842d-4b43-8b0a-d1d7c6cd2869
> [23:26:11 ERROR]: Could not pass event PlayerLoginEvent to IcarusMod v1.0
> org.bukkit.event.EventException
>         at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigotserver.jar:git-Spigot-b8f6402-a646500]
>         at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigotserver.jar:git-Spigot-b8f6402-a646500]
>         at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigotserver.jar:git-Spigot-b8f6402-a646500]
>         at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigotserver.jar:git-Spigot-b8f6402-a646500]
>         at net.minecraft.server.v1_8_R1.PlayerList.attemptLogin(PlayerList.java:413) [spigotserver.jar:git-Spigot-b8f6402-a646500]
>         at net.minecraft.server.v1_8_R1.LoginListener.b(LoginListener.java:97) [spigotserver.jar:git-Spigot-b8f6402-a646500]
>         at net.minecraft.server.v1_8_R1.LoginListener.c(LoginListener.java:41) [spigotserver.jar:git-Spigot-b8f6402-a646500]
>         at net.minecraft.server.v1_8_R1.NetworkManager.a(NetworkManager.java:159) [spigotserver.jar:git-Spigot-b8f6402-a646500]
>         at net.minecraft.server.v1_8_R1.ServerConnection.c(ServerConnection.java:82) [spigotserver.jar:git-Spigot-b8f6402-a646500]
>         at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:785) [spigotserver.jar:git-Spigot-b8f6402-a646500]
>         at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigotserver.jar:git-Spigot-b8f6402-a646500]
>         at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [spigotserver.jar:git-Spigot-b8f6402-a646500]
>         at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [spigotserver.jar:git-Spigot-b8f6402-a646500]
>         at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
> Caused by: java.lang.NullPointerException
>         at com.superiornetworks.icarus.ICM_Rank.getRank(ICM_Rank.java:57) ~[?:?]
>         at com.superiornetworks.icarus.ICM_Rank.isRankOrHigher(ICM_Rank.java:36) ~[?:?]
>         at com.superiornetworks.icarus.modules.LoginModule.onPlayerLoginEvent(LoginModule.java:26) ~[?:?]
>         at com.superiornetworks.icarus.listeners.PlayerListener.onPlayerLoginEvent(PlayerListener.java:46) ~[?:?]
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
>         at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
>         at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[spigotserver.jar:git-Spigot-b8f6402-a646500]
>         ... 13 more

**Comment by Hockeyfan360** [comment]
I fixed this here: https://github.com/Superior-Development/IcarusMod/commit/7457367b45c1f91b629a3bc2d34e4a21983b9c47. Feel free to open this issue again if the problem still persists (if for some reason it does, even though I tested it).
