### ISSUE TITLE
God mode broken

### ISSUE THREAD

**Issue by Wild1145** [Superior-Development/IcarusMod#79]
https://pravi.us/SCd

Simple as that.

**Comment by Hockeyfan360** [comment]
I think that this is the problem: 

http://imgur.com/lHhW3bb

if (!ICM_SqlHandler.hasDoomHammer(player.getName()))
            {
                playerMsg(sender, "&aEnabled god mode.");
                Connection c = ICM_SqlHandler.getConnection();
                PreparedStatement statement = c.prepareStatement("UPDATE `players` SET `godMode` = FALSE WHERE `playerName` = ?");
                statement.setString(1, player.getName());
                statement.executeUpdate();
            }

the false in there needs to be true, @CameronRedmore would that be right? (I am not that good with SQL)

**Comment by CameronRedmore** [comment]
This entire thing is just broken, I'll repair it later.
