### ISSUE TITLE
Development Mode

### ISSUE THREAD

**Issue by Wild1145** [Superior-Development/IcarusMod#8]
A bit like admin mode but with three options
- Everyone can connect but just gets a warning when they join the server
- Only admins can join and get a warning anyway
- Only Developers can join and get a warning.

If its in the second or third mode, when there are no developers online it would automatically switch to the first mode after 5 (maybe 10) mins.

**Comment by Hockeyfan360** [comment]
I have this covered. I have started this, and I am almost done. Do not commit please.
