### ISSUE TITLE
Imposter verification a bit broken

### ISSUE THREAD

**Issue by Wild1145** [Superior-Development/IcarusMod#81]
https://pravi.us/yfM

Means its a little broken...

**Comment by mgejay** [comment]
I dont see the bug - explain?

**Comment by Wild1145** [comment]
It adds you to Super admin regardless of your rank.

**Comment by Wild1145** [comment]
I am not too sure if this will even be an issue... @thecjgcjg will be managing everything through the panel anyway, so direct modification of the DB is possible to work around this issue...
