### ISSUE TITLE
Tab Colours

### ISSUE THREAD

**Issue by Wild1145** [Superior-Development/IcarusMod#82]
We need tab Colours. That is all.

**Comment by Scuph** [comment]
Colors*

**Comment by Hockeyfan360** [comment]
We could also do tab headers/footers. So, for the tab headers, would these colors work:

SA: &bname
STA: &2name
SRA: &dname
Developer: &5name
Manager: &4name

**Comment by Wild1145** [comment]
I like that, I heard that they were added but have yet to use them, so if we could do that as well (Pulling the header and footer from MySQL) that would be idea.

**Comment by Hockeyfan360** [comment]
Where would we pull it from? A settings table that doesn't exist? I could set that up if you wanted.

**Comment by Wild1145** [comment]
See #132 that I just opened :)

**Comment by Wild1145** [comment]
Going to give this one to @Paul19988 as he should be able to do it :)

**Comment by mgejay** [comment]
Who is this @Paul19988 @Wild1145?

**Comment by Fyrsta** [comment]
@Scuph Someone who can code, unlike some people here.

**Comment by Wild1145** [comment]
@Paul19988 has implmented the API side of this, I will be implmenting the actual setting of the tab system.

**Comment by Hockeyfan360** [comment]
@WickedGamingUK If you have nothing constructive to offer, then leave. I really don't appreciate such insults.

**Comment by Paul19988** [comment]
Players TAB colors now correspond to their rank, colors are set on player join.
