### ISSUE TITLE
Problems with Dev's and Managers

### ISSUE THREAD

**Issue by Wild1145** [Superior-Development/IcarusMod#83]
https://pravi.us/c1S

Need I say more.

**Comment by Hockeyfan360** [comment]
From what I see, your playerdata was null in the database. It works fine on my local server.

**Comment by Wild1145** [comment]
This is to super an imposter... I was in the database because I was manager before that. All I did was change the IP logged in the DB

**Comment by CameronRedmore** [comment]
Yeah, I kind of threw the imposter system together in a couple of minutes and I didn't really check it through properly :/ I'll fix this.

**Comment by Wild1145** [comment]
I think this is a duplicate of #84
