### ISSUE TITLE
Adding yourself to admin........

### ISSUE THREAD

**Issue by Wild1145** [Superior-Development/IcarusMod#84]
https://pravi.us/wCo

Wut...

**Comment by LegendIsAwesomes** [comment]
Ye, I wasnt abusing JUST TESTING.

**Comment by Wild1145** [comment]
@LegendIsAwesomes Not to worry, its a BETA test :) Would rather know now than not :)

**Comment by Wild1145** [comment]
The link has been deleted... Further testing will need to be done then... Irritating.

**Comment by Wild1145** [comment]
Im going to close this, I assume it was an issue with imposters.

**Comment by LegendIsAwesomes** [comment]
@Wild1145 at the time of, it was a problem of ops having permission to add themselves to admin status.

**Comment by Wild1145** [comment]
@LegendIsAwesomes Thankyou, this is something to be investigated.

**Comment by CameronRedmore** [comment]
Just checked this, the whole adding yourself to admin thing, the command doesn't appear to go through yet it displays the notifications that it has. I'll fix this now.
