### ISSUE TITLE
Rawsay type command

### ISSUE THREAD

**Issue by Wild1145** [Superior-Development/IcarusMod#91]
Something to use from console as a server wide raw text system could be handy.

**Comment by GotNoFriends** [comment]
I'll do this in the morning.

**Comment by GotNoFriends** [comment]
https://github.com/Superior-Development/IcarusMod/pull/105

**Comment by Hockeyfan360** [comment]
Console only? Senior from in game seems fine imo

**Comment by mgejay** [comment]
Console only would be the best option. @Hockeyfan360

**Comment by Hockeyfan360** [comment]
Server, or network wide?

**Comment by Wild1145** [comment]
This one would be server wide. Network wide would require this raised in PegasusMod.
