### ISSUE TITLE
Migrate all commands to the new command processor

### ISSUE THREAD

**Issue by Wild1145** [Superior-Development/IcarusMod#93]
Commands need to be migrated onto the new system to handle commands.

**Comment by GotNoFriends** [comment]
Camzies one?

**Comment by Wild1145** [comment]
Yeah.

**Comment by GotNoFriends** [comment]
Let's leave that to camzie then

**Comment by Wild1145** [comment]
This has been handled in the other issue for migrating off of bukkitlib command systems.
